[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"
openai = "^1.44.1"
python-dotenv = "^1.0.1"
boto3 = "^1.35.56"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
